spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssafy_web_db?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ssafy
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:\BOJ\
      max-file-size: 100MB
      max-request-size: 100MB

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                #        show_sql: true
                format_sql: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    servlet:
      multipart:
          file-size-threshold: 1MB
          location: C:\BOJ\
          max-file-size: 100MB
          max-request-size: 100MB

server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/ssafy.p12
    key-store-password: 123123
    key-alias: ssafy
    # trust-store: classpath:keystore/truststore.ts
    # trust-store-password: 123123

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
